@baseUrl = http://localhost:5000

###
# @name login
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email": "example@mail.com",
    "password": "123456"
}

###
# @name register
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "email": "admin1@gmail.com",
    "password": "123456",
    "password_confirmation": "123456",
    "name": "John Doe"
}
