@baseUrl = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImMzNTM4Zjk0LTEwODAtNDFmNy04ZDlhLTg0Yzc0YWFjMzQ1ZSIsIm5hbWUiOiJleGFtcGxlIiwiYWdlIjpudWxsLCJlbWFpbCI6ImV4YW1wbGVAbWFpbC5jb20iLCJleHAiOjE3MDEwOTczMjd9.MhhzN4VjgrOUfDQGe8MNghKDCt0ALJHlLm363UkBTAo

###
# @name createComment
POST {{baseUrl}}/comments
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "book_id": "2436c497-8d85-4cee-bf65-8a20f83a1fbe",
    "comment": "This is a comment 5"
}

