# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
 
development:
  <<: *default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> # default value: 5
  username: <%= ENV['PG_DB_USERNAME'] %>
  password: <%= ENV['PG_DB_PASSWORD'] %>
  # socket: /path/to/PG/socket # (optional, use only if needed)
  host: <%= ENV['PG_DB_HOST'] %>
  database:  <%= ENV['PG_DB_NAME'] %>
  port: <%= ENV['PG_DB_PORT'] %>

# Warning: The database defined as "test" will be erased and
test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  database: storage/production.sqlite3
